export const SAMPLE_README = [
  '# Markdown Dashboard',
  '',
  'A clean, **two-way** editor. Type Markdown on the left, or edit the *rendered* text on the right — both panes stay in sync.',
  '',
  '## Features',
  '',
  '- Live, editable preview',
  '- Formatting toolbar & keyboard-friendly source',
  '- Drag-and-drop `.md` import',
  '- Export to Markdown or PDF',
  '',
  '## Quick example',
  '',
  '> Editing on either side updates the other instantly.',
  '',
  'Inline `code`, a [link](https://example.com), and **bold** all work.',
  '',
  '```',
  'npm install',
  'npm run dev',
  '```',
  '',
  '---',
  '',
  '1. Open a file from the sidebar',
  '2. Write or paste Markdown',
  '3. Export when you are done',
].join('\n')

export const SAMPLE_NOTES = [
  '# Meeting notes',
  '',
  '**Date:** June 25, 2026',
  '',
  '## Discussion',
  '',
  '- Reviewed the new dashboard layout',
  '- Agreed on a *minimal* developer-tool aesthetic',
  '- Synced scrolling is a must-have',
  '',
  '## Action items',
  '',
  '1. Ship the split view',
  '2. Add export options',
  '3. Polish dark mode',
].join('\n')

export const SAMPLE_TODO = [
  '# Todo',
  '',
  '## This week',
  '',
  '- Wire up bidirectional sync',
  '- ~~Pick fonts~~ done',
  '- Test drag & drop',
  '',
  '## Backlog',
  '',
  '- Table support',
  '- Slash commands',
].join('\n')
