/**
 * Generate `cli/assets.generated.ts` from the built browser bundle in `dist/`.
 *
 * The CLI ships as a single self-contained executable, which cannot read `dist/`
 * off disk — there is no `dist/` next to a binary. Embedding the bundle as a
 * module solves that, and removes the whole asset-filesystem surface as a side
 * effect: the static route no longer resolves paths, follows symlinks, or reads
 * files, so the traversal and symlink-escape classes review found there twice
 * simply cannot occur. A request either names an embedded key or it 404s.
 *
 * Run via `pnpm build:cli`, which builds `dist/` first.
 */
import { createHash } from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'

const DIST = path.resolve(import.meta.dirname, '..', 'dist')
const OUT = path.resolve(import.meta.dirname, '..', 'cli', 'assets.generated.ts')

const CONTENT_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.map': 'application/json; charset=utf-8',
}

/**
 * Files that live in dist/ because Vercel serves them, but are not part of the
 * editor — the CLI should not embed or serve its own installer.
 */
const NOT_APP_ASSETS = new Set(['install.sh'])

/** Every file under `dir`, as paths relative to it with forward slashes. */
async function walk(dir, base = dir) {
  const out = []
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full, base)))
    else if (entry.isFile()) out.push(path.relative(base, full).split(path.sep).join('/'))
  }
  return out.filter((f) => !NOT_APP_ASSETS.has(f)).sort()
}

// A fresh clone has no dist/ yet, and `tsc` needs this module to exist before the
// web bundle is ever built — the two have a circular order. So emit an empty
// manifest rather than failing: it satisfies the type checker, and cli/index.ts
// refuses to start when index.html is not embedded, so an empty build cannot
// masquerade as a working one.
const files = await walk(DIST).catch(() => null)
if (files === null || !files.includes('index.html')) {
  await fs.writeFile(
    OUT,
    `/**
 * GENERATED by scripts/embed-assets.mjs — do not edit.
 *
 * PLACEHOLDER: no built bundle was present at generation time. The CLI will
 * refuse to start with this in place. Run \`pnpm build\` then \`pnpm build:cli\`.
 */

export interface EmbeddedAsset {
  contentType: string
  /** Base64 so the module stays valid TypeScript source. */
  base64: string
}

export const ASSETS: ReadonlyMap<string, EmbeddedAsset> = new Map()
`,
    'utf8'
  )
  process.stdout.write(
    `no built bundle at ${DIST} — wrote a placeholder manifest. ` +
      `Run \`pnpm build\` before \`pnpm build:cli\` to embed the real one.\n`
  )
  process.exit(0)
}

const entries = []
let total = 0
for (const rel of files) {
  const bytes = await fs.readFile(path.join(DIST, rel))
  total += bytes.length
  const type = CONTENT_TYPES[path.extname(rel).toLowerCase()] ?? 'application/octet-stream'
  entries.push(
    `  [${JSON.stringify(rel)}, { contentType: ${JSON.stringify(type)}, base64: '${bytes.toString('base64')}' }],`
  )
}

// Hash the inputs so a stale generated file is detectable rather than silent.
const digest = createHash('sha256')
for (const rel of files) digest.update(rel).update(await fs.readFile(path.join(DIST, rel)))

const banner = `/**
 * GENERATED by scripts/embed-assets.mjs — do not edit.
 *
 * The built browser bundle, embedded so the CLI is self-contained and never
 * reads assets from the filesystem. Regenerate with \`pnpm build:cli\`.
 *
 * Source: ${files.length} files, ${total} bytes
 * Digest: ${digest.digest('hex').slice(0, 16)}
 */
`

await fs.writeFile(
  OUT,
  `${banner}
export interface EmbeddedAsset {
  contentType: string
  /** Base64 so the module stays valid TypeScript source. */
  base64: string
}

export const ASSETS: ReadonlyMap<string, EmbeddedAsset> = new Map([
${entries.join('\n')}
])
`,
  'utf8'
)

process.stdout.write(
  `embedded ${files.length} asset(s), ${(total / 1024).toFixed(0)} KiB -> cli/assets.generated.ts\n`
)
