/**
 * Generate `cli/version.generated.ts` from package.json.
 *
 * The CLI ships as a single executable with no package.json beside it, so the
 * version has to be baked in at build time — there is nothing to read at runtime.
 * Generating it from the one source of truth is what keeps `--version` honest:
 * a hand-maintained constant drifts, and a binary that misreports its own version
 * makes every bug report ambiguous.
 *
 * Run via `pnpm embed`, alongside scripts/embed-assets.mjs.
 */
import fs from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT = path.join(ROOT, 'cli', 'version.generated.ts')

const pkg = JSON.parse(await fs.readFile(path.join(ROOT, 'package.json'), 'utf8'))
const version = pkg.version

if (typeof version !== 'string' || !/^\d+\.\d+\.\d+/.test(version)) {
  throw new Error(`package.json version is not a semver string: ${JSON.stringify(version)}`)
}

await fs.writeFile(
  OUT,
  `/**
 * GENERATED by scripts/embed-version.mjs — do not edit.
 *
 * The version this build was made from, taken from package.json. Regenerate with
 * \`pnpm embed\`.
 */

export const VERSION = '${version}'
`,
  'utf8'
)

process.stdout.write(`version ${version} -> cli/version.generated.ts\n`)
